packages:
  - browser
  - vscode-extension
  - examples/*
  - plugins/*

patchedDependencies:
  '@openai/agents-core': patches/@openai__agents-core.patch
  marked-terminal: patches/marked-terminal.patch
